import { supabase } from './supabase.js';
import { state, loadProducts, loadCustomers, loadSuppliers } from './store.js';
import { $, $$, escapeHtml, money, whatsappUrl } from './utils.js';
import { modal, closeModal, toast } from './ui.js';

export async function newCustomer(){
 modal('Nuevo cliente',`<form id="customerForm" class="form-grid"><label>Nombre completo<input name="full_name" required></label><label>WhatsApp<input name="whatsapp" inputmode="tel" placeholder="573001234567" required></label><label>Correo<input name="email" type="email"></label><label>Ciudad<input name="city" value="Cali"></label><label class="full">Dirección / sector<input name="address_line"></label><label class="full">Observaciones<textarea name="notes" rows="3"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Guardar cliente</button></div></form>`);
 $('#customerForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const {data,error}=await supabase.from('customers').insert({full_name:f.full_name,whatsapp:f.whatsapp,email:f.email||null,notes:f.notes||null,created_by:state.profile.id}).select().single();if(error)throw error;if(f.address_line){const {error:aerr}=await supabase.from('customer_addresses').insert({customer_id:data.id,address_line:f.address_line,city:f.city||'Cali',is_default:true});if(aerr)throw aerr;}closeModal();toast('Cliente registrado correctamente');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export async function newSupplier(){
 modal('Nuevo proveedor',`<form id="supplierForm" class="form-grid"><label>Nombre comercial<input name="business_name" required></label><label>Persona de contacto<input name="contact_name"></label><label>WhatsApp<input name="whatsapp" placeholder="573001234567" required></label><label>Ciudad<input name="city"></label><label>Días habituales de entrega<input name="average_delivery_days" type="number" min="0" value="1"></label><label>Correo<input name="email" type="email"></label><label class="full">Información de pago<textarea name="payment_information" rows="2"></textarea></label><label class="full">Observaciones<textarea name="notes" rows="3"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Guardar proveedor</button></div></form>`);
 $('#supplierForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const {error}=await supabase.from('suppliers').insert({...f,average_delivery_days:Number(f.average_delivery_days)||null,created_by:state.profile.id});if(error)throw error;closeModal();toast('Proveedor registrado');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export async function newProduct(){
 await loadSuppliers(); modal('Nuevo producto',`<form id="productForm" class="form-grid"><label>Código catálogo<input name="catalog_code"></label><label>SKU interno<input name="sku"></label><label class="full">Nombre<input name="name" required></label><label>Línea<select name="business_line"><option>Beauty Care</option><option>Style</option></select></label><label>Categoría<input name="category"></label><label>Marca<input name="brand"></label><label>Precio LIHEN<input name="sale_price" type="number" min="0" required></label><label>Costo actual<input name="current_cost" type="number" min="0"></label><label>Stock físico inicial<input name="physical_stock" type="number" min="0" value="0"></label><label>Stock mínimo<input name="minimum_stock" type="number" min="0" value="0"></label><label>Proveedor principal<select name="supplier_id"><option value="">Sin asignar</option>${state.suppliers.map(s=>`<option value="${s.id}">${escapeHtml(s.business_name)}</option>`).join('')}</select></label><label>Visible en la página<select name="visible_on_website"><option value="true">Sí</option><option value="false">No</option></select></label><label class="full">Descripción<textarea name="description" rows="4"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Guardar producto</button></div></form>`);
 $('#productForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const payload={catalog_code:f.catalog_code||null,sku:f.sku||null,name:f.name,business_line:f.business_line,category:f.category||null,brand:f.brand||null,sale_price:Number(f.sale_price),current_cost:f.current_cost?Number(f.current_cost):null,minimum_stock:Number(f.minimum_stock)||0,description:f.description||null,status:'activo',visible_on_website:f.visible_on_website==='true',created_by:state.profile.id,updated_by:state.profile.id};const {data,error}=await supabase.from('products').insert(payload).select().single();if(error)throw error;const {error:ierr}=await supabase.from('inventory').insert({product_id:data.id,physical_stock:Number(f.physical_stock)||0,updated_by:state.profile.id});if(ierr)throw ierr;if(f.supplier_id){const {error:serr}=await supabase.from('supplier_products').insert({supplier_id:f.supplier_id,product_id:data.id,last_cost:payload.current_cost,preferred:true});if(serr)throw serr;}closeModal();toast('Producto registrado');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export async function newOrder(){
 await Promise.all([loadProducts(),loadCustomers()]);
 modal('Crear pedido LIHEN',`<form id="orderForm"><div class="form-grid"><label class="full">Cliente<select name="customer_id" required><option value="">Selecciona un cliente</option>${state.customers.map(c=>`<option value="${c.id}">${escapeHtml(c.full_name)} · ${escapeHtml(c.whatsapp)}</option>`).join('')}</select></label></div><div class="section-title"><div><p class="eyebrow">PRODUCTOS</p><h3>Selección del pedido</h3></div><button type="button" class="button secondary" id="addOrderItem">+ Agregar producto</button></div><div id="orderItems" class="order-builder"></div><div class="form-grid"><label>Tipo de descuento<select name="discount_type" id="discountType"><option value="ninguno">Sin descuento</option><option value="porcentaje">Porcentaje</option><option value="valor_fijo">Valor fijo</option></select></label><label>Valor del descuento<input name="discount_value" id="discountValue" type="number" min="0" value="0"></label><label>Costo domicilio<input name="delivery_cost" id="deliveryCost" type="number" min="0" value="0"></label><label>Método de pago<select name="payment_method"><option value="sin_definir">Por confirmar</option><option value="efectivo_contra_entrega">Efectivo contra entrega</option><option value="nequi">Nequi</option><option value="llave_bancaria">Llave bancaria</option><option value="transferencia">Transferencia</option></select></label><label class="full">Notas internas<textarea name="internal_notes" rows="3"></textarea></label></div><div id="orderTotals" class="order-totals"></div><div class="form-actions"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Crear pedido</button></div></form>`,{wide:true});
 const items=$('#orderItems');
 function addRow(){const row=document.createElement('div');row.className='order-row';row.innerHTML=`<label>Producto<select class="item-product" required><option value="">Selecciona</option>${state.products.map(p=>{const i=p.inventory?.[0]||{};return `<option value="${p.id}" data-price="${p.sale_price}" data-stock="${i.available_stock||0}" data-name="${escapeHtml(p.name)}">${escapeHtml(p.name)} · Libre ${i.available_stock||0}</option>`}).join('')}</select></label><label>Cantidad<input class="item-qty" type="number" min="1" value="1" required></label><label>Precio<input class="item-price" type="number" min="0" value="0" required></label><div class="stock-note">Selecciona un producto</div><button type="button" class="remove-row">×</button>`;items.append(row);const sel=$('.item-product',row),qty=$('.item-qty',row),price=$('.item-price',row),note=$('.stock-note',row);sel.addEventListener('change',()=>{const o=sel.selectedOptions[0];price.value=o?.dataset.price||0;const available=Number(o?.dataset.stock)||0;note.textContent=available>0?`${available} disponible(s) físicamente`:'Se debe conseguir con proveedor';calculate();});[qty,price].forEach(x=>x.addEventListener('input',calculate));$('.remove-row',row).addEventListener('click',()=>{row.remove();calculate()});calculate();}
 function calculate(){let subtotal=0;$$('.order-row',items).forEach(r=>subtotal+=(Number($('.item-qty',r).value)||0)*(Number($('.item-price',r).value)||0));const type=$('#discountType').value,value=Number($('#discountValue').value)||0,discount=type==='porcentaje'?subtotal*value/100:type==='valor_fijo'?value:0,delivery=Number($('#deliveryCost').value)||0,total=Math.max(0,subtotal-discount+delivery);$('#orderTotals').innerHTML=`<div><span>Subtotal</span><b>${money(subtotal)}</b></div><div><span>Descuento</span><b>− ${money(discount)}</b></div><div><span>Domicilio</span><b>${money(delivery)}</b></div><div class="total"><span>Total</span><strong>${money(total)}</strong></div>`;return{subtotal,discount,delivery,total};}
 $('#addOrderItem').addEventListener('click',addRow);['discountType','discountValue','deliveryCost'].forEach(id=>$('#'+id).addEventListener('input',calculate));addRow();
 $('#orderForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),calc=calculate(),rows=$$('.order-row',items);if(!rows.length)return toast('Agrega al menos un producto','danger');try{const payload=rows.map(r=>{const sel=$('.item-product',r),opt=sel.selectedOptions[0];return{product_id:sel.value,variant_id:null,variant_snapshot:null,quantity:Number($('.item-qty',r).value),unit_price:Number($('.item-price',r).value)};});const {data:order,error}=await supabase.rpc('create_order_atomic',{p_customer_id:f.customer_id,p_delivery_address_id:null,p_payment_method:f.payment_method,p_discount_type:f.discount_type,p_discount_value:Number(f.discount_value)||0,p_delivery_cost:calc.delivery,p_discount_reason:null,p_customer_notes:null,p_internal_notes:f.internal_notes||null,p_items:payload});if(error)throw error;closeModal();toast(`Pedido ${order.order_number} creado y stock reservado`);document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export function importCatalog(){modal('Importar catálogo maestro',`<div class="import-guide"><div class="callout"><b>Importación inicial controlada</b><p>Esta función cargará productos del archivo CSV sin modificar el stock físico. Después se realizará la conciliación del inventario.</p></div><label>Archivo catalogo_maestro.csv<input id="catalogFile" type="file" accept=".csv,text/csv"></label><div id="importPreview"></div><div class="form-actions"><button class="button ghost" data-close-modal>Cancelar</button><button class="button primary" id="startImport" disabled>Importar productos</button></div></div>`);let rows=[];$('#catalogFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),headers=parseLine(lines.shift());rows=lines.map(parseLine).filter(r=>r.length>=7).map(cols=>Object.fromEntries(headers.map((h,i)=>[h,cols[i]||''])));$('#importPreview').innerHTML=`<div class="alert success">Se detectaron <b>${rows.length}</b> productos. El stock inicial quedará en 0 hasta la conciliación física.</div>`;$('#startImport').disabled=!rows.length;});$('#startImport').addEventListener('click',async()=>{try{const mapped=rows.map(r=>({catalog_code:r.ID||null,name:r.Nombre,business_line:r['Línea']||null,category:r['Categoría']||null,brand:r.Marca||null,sale_price:Number(String(r.Precio||0).replace(/\D/g,''))||0,status:String(r.Estado).toLowerCase()==='activo'?'activo':'oculto',visible_on_website:String(r.Estado).toLowerCase()==='activo',catalog_availability_text:r.Disponibilidad||'Consulta disponibilidad por WhatsApp',description:r['Descripción']||null,category_folder:r['Carpeta categoría']||null,product_folder:r['Carpeta producto']||null,main_image_url:(r['Imágenes']||'').split('|')[0]||null,created_by:state.profile.id,updated_by:state.profile.id}));for(let i=0;i<mapped.length;i+=50){const {error}=await supabase.from('products').upsert(mapped.slice(i,i+50),{onConflict:'catalog_code'});if(error)throw error;}closeModal();toast(`${mapped.length} productos importados`);document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});function parseLine(line){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===';'&&!quoted){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out;}}

export async function inventoryAdjustment(){
 await loadProducts();
 modal('Ajustar inventario',`<form id="adjustForm" class="form-grid"><label class="full">Producto<select name="product_id" required><option value="">Selecciona un producto</option>${state.products.map(p=>{const i=p.inventory?.[0]||{};return `<option value="${p.id}" data-inventory="${i.id||''}">${escapeHtml(p.name)} · físico ${i.physical_stock||0}</option>`}).join('')}</select></label><label>Tipo de ajuste<select name="direction"><option value="add">Sumar unidades</option><option value="subtract">Restar unidades</option></select></label><label>Cantidad<input name="quantity" type="number" min="1" value="1" required></label><label class="full">Motivo<textarea name="reason" rows="3" required placeholder="Ejemplo: conteo físico, producto usado en inauguración, devolución…"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Registrar ajuste</button></div></form>`);
 $('#adjustForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const product=state.products.find(p=>p.id===f.product_id),inventory=product?.inventory?.[0];if(!inventory?.id){toast('Este producto aún no tiene registro de inventario.','danger');return;}const qty=(f.direction==='subtract'?-1:1)*Number(f.quantity);try{const {error}=await supabase.rpc('adjust_inventory_atomic',{p_inventory_id:inventory.id,p_user_id:state.profile.id,p_quantity:qty,p_reason:f.reason});if(error)throw error;closeModal();toast('Inventario actualizado con trazabilidad');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
