import { supabase } from './supabase.js';
import { state, loadProducts, loadCustomers, loadSuppliers } from './store.js';
import { $, escapeHtml } from './utils.js';
import { modal, closeModal, toast } from './ui.js';
import { openOrderEditor } from './order-workflow.js';
import { createProductAtomic } from './repositories/product-repository.js';
import { suggestNextProductSku } from './services/product-code-service.js';

export async function newCustomer(){
 modal('Nuevo cliente',`<form id="customerForm" class="form-grid"><label>Nombre completo<input name="full_name" required></label><label>WhatsApp<input name="whatsapp" inputmode="tel" placeholder="573001234567" required></label><label>Correo<input name="email" type="email"></label><label>Ciudad<input name="city" value="Cali"></label><label class="full">Dirección / sector<input name="address_line"></label><label class="full">Observaciones<textarea name="notes" rows="3"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Guardar cliente</button></div></form>`);
 $('#customerForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const {data,error}=await supabase.from('customers').insert({full_name:f.full_name,whatsapp:f.whatsapp,email:f.email||null,notes:f.notes||null,created_by:state.profile.id}).select().single();if(error)throw error;if(f.address_line){const {error:aerr}=await supabase.from('customer_addresses').insert({customer_id:data.id,address_line:f.address_line,city:f.city||'Cali',is_default:true});if(aerr)throw aerr;}closeModal();toast('Cliente registrado correctamente');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export async function newSupplier(){
 modal('Nuevo proveedor',`<form id="supplierForm" class="form-grid"><label>Nombre comercial<input name="business_name" required></label><label>Persona de contacto<input name="contact_name"></label><label>WhatsApp<input name="whatsapp" placeholder="573001234567" required></label><label>Ciudad<input name="city"></label><label>Días habituales de entrega<input name="average_delivery_days" type="number" min="0" value="1"></label><label>Correo<input name="email" type="email"></label><label class="full">Información de pago<textarea name="payment_information" rows="2"></textarea></label><label class="full">Observaciones<textarea name="notes" rows="3"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Guardar proveedor</button></div></form>`);
 $('#supplierForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const {error}=await supabase.from('suppliers').insert({...f,average_delivery_days:Number(f.average_delivery_days)||null,created_by:state.profile.id});if(error)throw error;closeModal();toast('Proveedor registrado');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export async function newProduct(){
 await Promise.all([loadSuppliers(),loadProducts()]);
 modal('Nuevo producto',`<form id="productForm" class="form-grid"><label>Código catálogo<input name="catalog_code" autocomplete="off"><small>Opcional. Déjalo vacío si este producto aún no tiene código de catálogo público.</small></label><label>SKU interno<input name="sku" autocomplete="off" required><small id="skuSuggestion">Se calcula automáticamente según la línea seleccionada.</small></label><label class="full">Nombre<input name="name" required></label><label>Línea<select name="business_line"><option>Beauty Care</option><option>Style</option></select></label><label>Categoría<input name="category"></label><label>Marca<input name="brand"></label><label>Precio LIHEN<input name="sale_price" type="number" min="0" required></label><label>Costo actual<input name="current_cost" type="number" min="0"></label><label>Stock físico inicial<input name="physical_stock" type="number" min="0" value="0"></label><label>Stock mínimo<input name="minimum_stock" type="number" min="0" value="0"></label><label>Proveedor principal<select name="supplier_id"><option value="">Sin asignar</option>${state.suppliers.map(s=>`<option value="${s.id}">${escapeHtml(s.business_name)}</option>`).join('')}</select></label><label>Visible en la página<select name="visible_on_website"><option value="false" selected>No</option><option value="true">Sí</option></select></label><label class="full">Imagen principal pública<input name="main_image_url" type="url" placeholder="https://... o URL pública existente"></label><div class="callout full"><b>Publicación segura</b><p>Un producto nuevo queda oculto por defecto. Para aparecer en la tienda debe estar activo, marcado como visible y tener una fotografía pública válida.</p></div><label class="full">Descripción<textarea name="description" rows="4"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Guardar producto</button></div></form>`);
 const form=$('#productForm');
 const lineSelect=form.elements.business_line;
 const skuInput=form.elements.sku;
 const suggestionText=$('#skuSuggestion');
 let lastSuggested='';
 const applySuggestion=()=>{const next=suggestNextProductSku(state.products,lineSelect.value);const current=skuInput.value.trim();if(!current||current===lastSuggested)skuInput.value=next;lastSuggested=next;if(suggestionText)suggestionText.textContent=next?`Siguiente SKU sugerido para ${lineSelect.value}: ${next}`:'No hay una secuencia configurada para esta línea.';};
 applySuggestion();
 lineSelect.addEventListener('change',applySuggestion);
 form.addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{const product={catalog_code:f.catalog_code?.trim()||null,sku:f.sku?.trim()||null,name:f.name?.trim(),business_line:f.business_line,category:f.category?.trim()||null,brand:f.brand?.trim()||null,sale_price:Number(f.sale_price),current_cost:f.current_cost===''?null:Number(f.current_cost),minimum_stock:Number(f.minimum_stock)||0,main_image_url:f.main_image_url?.trim()||null,description:f.description?.trim()||null,status:'activo',visible_on_website:f.visible_on_website==='true'};await createProductAtomic({product,initialPhysicalStock:Number(f.physical_stock)||0,supplierId:f.supplier_id||null});closeModal();toast('Producto registrado');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
export async function newOrder(){
  await Promise.all([loadProducts(),loadCustomers()]);
  openOrderEditor();
}
export function importCatalog(){modal('Importar catálogo maestro',`<div class="import-guide"><div class="callout"><b>Importación inicial controlada</b><p>Esta función cargará productos del archivo CSV sin modificar el stock físico. Después se realizará la conciliación del inventario.</p></div><label>Archivo catalogo_maestro.csv<input id="catalogFile" type="file" accept=".csv,text/csv"></label><div id="importPreview"></div><div class="form-actions"><button class="button ghost" data-close-modal>Cancelar</button><button class="button primary" id="startImport" disabled>Importar productos</button></div></div>`);let rows=[];$('#catalogFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),headers=parseLine(lines.shift());rows=lines.map(parseLine).filter(r=>r.length>=7).map(cols=>Object.fromEntries(headers.map((h,i)=>[h,cols[i]||''])));$('#importPreview').innerHTML=`<div class="alert success">Se detectaron <b>${rows.length}</b> productos. El stock inicial quedará en 0 hasta la conciliación física.</div>`;$('#startImport').disabled=!rows.length;});$('#startImport').addEventListener('click',async()=>{try{const mapped=rows.map(r=>({catalog_code:r.ID||null,name:r.Nombre,business_line:r['Línea']||null,category:r['Categoría']||null,brand:r.Marca||null,sale_price:Number(String(r.Precio||0).replace(/\D/g,''))||0,status:String(r.Estado).toLowerCase()==='activo'?'activo':'oculto',visible_on_website:String(r.Estado).toLowerCase()==='activo',catalog_availability_text:r.Disponibilidad||'Consulta disponibilidad por WhatsApp',description:r['Descripción']||null,category_folder:r['Carpeta categoría']||null,product_folder:r['Carpeta producto']||null,main_image_url:(r['Imágenes']||'').split('|')[0]||null,created_by:state.profile.id,updated_by:state.profile.id}));for(let i=0;i<mapped.length;i+=50){const {error}=await supabase.from('products').upsert(mapped.slice(i,i+50),{onConflict:'catalog_code'});if(error)throw error;}closeModal();toast(`${mapped.length} productos importados`);document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});function parseLine(line){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===';'&&!quoted){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out;}}

export async function inventoryAdjustment(){
 await loadProducts();
 modal('Ajustar inventario',`<form id="adjustForm" class="form-grid"><label class="full">Producto<select name="product_id" required><option value="">Selecciona un producto</option>${state.products.map(p=>{const i=p.inventory?.[0]||{};return `<option value="${p.id}" data-inventory="${i.id||''}">${escapeHtml(p.name)} · físico ${i.physical_stock||0}</option>`}).join('')}</select></label><label>Tipo de ajuste<select name="direction"><option value="add">Sumar unidades</option><option value="subtract">Restar unidades</option></select></label><label>Cantidad<input name="quantity" type="number" min="1" value="1" required></label><label class="full">Motivo<textarea name="reason" rows="3" required placeholder="Ejemplo: conteo físico, producto usado en inauguración, devolución…"></textarea></label><div class="form-actions full"><button type="button" class="button ghost" data-close-modal>Cancelar</button><button class="button primary">Registrar ajuste</button></div></form>`);
 $('#adjustForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const product=state.products.find(p=>p.id===f.product_id),inventory=product?.inventory?.[0];if(!inventory?.id){toast('Este producto aún no tiene registro de inventario.','danger');return;}const qty=(f.direction==='subtract'?-1:1)*Number(f.quantity);try{const {error}=await supabase.rpc('adjust_inventory_atomic',{p_inventory_id:inventory.id,p_user_id:state.profile.id,p_quantity:qty,p_reason:f.reason});if(error)throw error;closeModal();toast('Inventario actualizado con trazabilidad');document.dispatchEvent(new CustomEvent('lihen:refresh'));}catch(err){toast(err.message,'danger')}});
}
