import { state, loadDashboard, loadProducts, loadOrders, loadQuickSales, loadCustomers, loadSuppliers, loadMovements, loadReports } from './store.js';
import { $, escapeHtml, money, dateTime, statusLabel, whatsappUrl } from './utils.js';
import { badge, empty, formatMovement, metric, modal, spinner, totals } from './ui.js';
import { APP_CONFIG } from './config.js';
export { showOrder } from './order-workflow.js';
import { quickSaleReceipt } from './sales.js';

export async function renderRoute(){
 const root=$('#viewRoot'); if(root) root.innerHTML=spinner();
 const views={dashboard,orders,'quick-sales':quickSales,inventory,suppliers,customers,receipts,movements,reports,settings};
 try{return await views[state.route]();}catch(e){console.error(e); return `<div class="alert danger"><b>No pudimos cargar este módulo.</b><br>${escapeHtml(e.message)}</div>`;}
}
async function dashboard(){ const d=await loadDashboard(); return `<section class="welcome"><div><p class="eyebrow">RESUMEN OPERATIVO</p><h2>Hola, ${escapeHtml((state.profile?.full_name||'Cofundadora').split(' ')[0])}</h2><p>Estas son las prioridades de LIHEN en este momento.</p></div><button class="button secondary" data-route="orders">Ver pedidos activos →</button></section><div class="quick-actions"><button class="quick-action" data-action="new-order">▤<span>Nuevo pedido</span></button><button class="quick-action" data-action="new-quick-sale">🛒<span>Venta rápida</span></button><button class="quick-action" data-action="new-customer">♡<span>Nuevo cliente</span></button><button class="quick-action" data-action="inventory-adjustment">↺<span>Ingresar stock</span></button><button class="quick-action" data-action="import-bundled-inventory">✓<span>Cargar inventario inicial</span></button><button class="quick-action" data-action="import-inventory">⇧<span>Importar nuevo Excel</span></button></div>
<div class="metrics-grid">${metric('▤','Pedidos activos',d.activeOrders,'Requieren seguimiento','rose')}${metric('✓','Pedidos completos',d.readyOrders,'Listos para confirmar','green')}${metric('▦','Unidades disponibles',d.unitsAvailable,'Stock físico libre','gold')}${metric('!','Alertas de inventario',d.lowStock,'En mínimo o sin stock','red')}${metric('🛒','Ventas rápidas hoy',d.quickSalesToday,money(d.quickSalesRevenue),'green')}</div>
<div class="dashboard-grid"><section class="panel span-2"><header class="panel-head"><div><p class="eyebrow">OPERACIÓN</p><h3>Pedidos recientes</h3></div><button class="text-button" data-route="orders">Ver todos</button></header>${ordersTable(d.recentOrders)}</section><section class="panel"><header class="panel-head"><div><p class="eyebrow">ACTIVIDAD</p><h3>Últimos movimientos</h3></div></header><div class="activity-list">${d.movements.length?d.movements.map(formatMovement).join(''):empty('↺','Sin movimientos','Los cambios de inventario aparecerán aquí.')}</div></section></div>
<div class="insight-strip"><div><span>Productos visibles en web</span><b>${d.visibleProducts}</b></div><div><span>Unidades pendientes de recibir</span><b>${d.pendingToReceive}</b></div><div><span>Clientes registrados</span><b>${d.customers}</b></div><div><span>Compromiso de entrega</span><b>Hasta 3 días hábiles</b></div></div>`; }
function ordersTable(rows){ if(!rows?.length)return empty('▤','No hay pedidos','Crea el primer pedido cuando llegue una consulta por WhatsApp.','<button class="button primary" data-action="new-order">Crear pedido</button>'); return `<div class="table-scroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Estado</th><th>Total</th><th>Fecha</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${escapeHtml(o.order_number)}</b></td><td>${escapeHtml(o.customer?.full_name||'—')}</td><td>${badge(o.status)}</td><td><b>${money(o.total)}</b></td><td>${dateTime(o.created_at)}</td><td><button class="row-action" data-order-id="${o.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div>`; }
async function orders(){await loadOrders(); return `<section class="page-tools"><div class="search"><span>⌕</span><input id="orderSearch" placeholder="Buscar por número de pedido"></div><select id="orderStatus"><option value="">Todos los estados</option>${['solicitud_recibida','validando_disponibilidad','pendiente_proveedor','productos_solicitados','recepcion_parcial','pedido_completo','esperando_medio_pago','confirmado_cliente','preparando_entrega','enviado','entregado','cancelado'].map(x=>`<option value="${x}">${statusLabel(x)}</option>`).join('')}</select><button class="button primary" data-action="new-order">+ Nuevo pedido</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">PEDIDOS LIHEN</p><h3>${state.orders.length} registros</h3></div></header><div id="ordersContent">${ordersTable(state.orders)}</div></section>`;}

function quickSalesTable(rows){
  if(!rows?.length)return empty('🛒','No hay ventas rápidas','Registra una venta presencial pagada al instante.','<button class="button primary" data-action="new-quick-sale">Registrar venta</button>');
  return `<div class="table-scroll"><table><thead><tr><th>Venta</th><th>Cliente</th><th>Pago</th><th>Total</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td><b>${escapeHtml(s.sale_number)}</b></td><td>${escapeHtml(s.customer?.full_name||'Consumidor final')}</td><td>${escapeHtml(String(s.payment_method||'').replaceAll('_',' '))}</td><td><b>${money(s.total)}</b></td><td>${dateTime(s.created_at)}</td><td>${badge(s.status)}</td><td><button class="row-action" data-quick-sale-id="${s.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div>`;
}
async function quickSales(){
  await loadQuickSales();
  return `<section class="page-tools"><div class="search"><span>⌕</span><input id="quickSaleSearch" placeholder="Buscar por número de venta"></div><button class="button primary" data-action="new-quick-sale">+ Nueva venta rápida</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">VENTAS PRESENCIALES</p><h3>${state.quickSales.length} registros</h3></div><div class="callout compact-callout"><b>Pago inmediato</b><p>Descuenta stock al guardar. No crea reservas ni exige teléfono.</p></div></header>${quickSalesTable(state.quickSales)}</section>`;
}

async function inventory(){await loadProducts(); return `<section class="page-tools"><div class="search"><span>⌕</span><input id="productSearch" placeholder="Buscar producto"></div><select id="productVisibility"><option value="">Todos</option><option value="visible">Visibles en la web</option><option value="hidden">Ocultos</option></select><button class="button secondary" data-action="import-bundled-inventory">Cargar inventario inicial</button><button class="button secondary" data-action="import-inventory">Importar nuevo Excel</button><button class="button primary" data-action="new-product">+ Nuevo producto</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">INVENTARIO Y CATÁLOGO</p><h3>${state.products.length} productos</h3></div><button class="button secondary" data-action="import-catalog">Importar catálogo CSV</button></header>${productTable(state.products)}</section>`;}
function productTable(rows){if(!rows.length)return empty('▦','Sin productos','Importa el catálogo maestro o registra un producto.');return `<div class="table-scroll"><table><thead><tr><th>Producto</th><th>Estado web</th><th>Físico</th><th>Reservado</th><th>Libre</th><th>Pendiente</th><th>Precio</th><th></th></tr></thead><tbody>${rows.map(p=>{const i=p.inventory?.[0]||{};return `<tr><td><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.catalog_code||p.sku||'Sin código')} · ${escapeHtml(p.category||'Sin categoría')}</small></td><td>${p.visible_on_website?'<span class="status success">Publicado</span>':'<span class="status neutral">Oculto</span>'}</td><td>${i.physical_stock??0}</td><td>${i.reserved_stock??0}</td><td><b>${i.available_stock??0}</b></td><td>${i.pending_stock??0}</td><td><b>${money(p.sale_price)}</b></td><td><button class="row-action" data-edit-product="${p.id}">Editar</button></td></tr>`}).join('')}</tbody></table></div>`;}
async function suppliers(){await loadSuppliers();return `<section class="page-tools"><div class="search"><span>⌕</span><input id="supplierSearch" placeholder="Buscar proveedor"></div><button class="button secondary" data-action="import-suppliers">Importar</button><button class="button primary" data-action="new-supplier">+ Nuevo proveedor</button></section><div class="cards-grid">${state.suppliers.length?state.suppliers.map(s=>`<article class="supplier-card"><header><div class="supplier-logo">${escapeHtml(s.business_name.slice(0,2).toUpperCase())}</div>${badge(s.active?'activo':'oculto')}</header><h3>${escapeHtml(s.business_name)}</h3><p>${escapeHtml(s.contact_name||'Sin contacto registrado')}</p><dl><div><dt>WhatsApp</dt><dd>${escapeHtml(s.whatsapp)}</dd></div><div><dt>Ciudad</dt><dd>${escapeHtml(s.city||'—')}</dd></div><div><dt>Entrega habitual</dt><dd>${s.average_delivery_days??'—'} días</dd></div><div><dt>Productos asociados</dt><dd>${s.supplier_products?.length||0}</dd></div></dl><footer><a class="button whatsapp" target="_blank" href="${whatsappUrl(s.whatsapp,'Hola, buen día. Somos LIHEN.CO y queremos consultar disponibilidad de algunos productos.')}">Consultar por WhatsApp</a><button class="button ghost" data-edit-supplier="${s.id}">Editar</button></footer></article>`).join(''):empty('◇','Sin proveedores','Registra proveedores para generar solicitudes por WhatsApp.')}</div>`;}
async function customers(){await loadCustomers();return `<section class="page-tools"><div class="search"><span>⌕</span><input id="customerSearch" placeholder="Buscar cliente o WhatsApp"></div><button class="button secondary" data-action="import-customers">Importar</button><button class="button primary" data-action="new-customer">+ Nuevo cliente</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">BASE DE CLIENTES</p><h3>${state.customers.length} clientes</h3></div></header><div class="table-scroll"><table><thead><tr><th>Cliente</th><th>WhatsApp</th><th>Dirección principal</th><th>Notas</th><th></th></tr></thead><tbody>${state.customers.map(c=>`<tr><td><b>${escapeHtml(c.full_name)}</b><small>${escapeHtml(c.email||'Sin correo')}</small></td><td>${escapeHtml(c.whatsapp)}</td><td>${escapeHtml(c.addresses?.find(a=>a.is_default)?.address_line||c.addresses?.[0]?.address_line||'—')}</td><td>${escapeHtml(c.notes||'—')}</td><td><div class="row-actions"><button class="row-action" data-edit-customer="${c.id}">Editar</button><a class="row-action" target="_blank" href="${whatsappUrl(c.whatsapp,`Hola ${c.full_name}, te saludamos desde LIHEN.CO.`)}">WhatsApp</a></div></td></tr>`).join('')}</tbody></table></div></section>`;}
async function receipts(){await loadOrders();const eligible=state.orders.filter(o=>['pedido_completo','esperando_medio_pago','confirmado_cliente','preparando_entrega','enviado','entregado'].includes(o.status));return `<section class="panel"><header class="panel-head"><div><p class="eyebrow">COMPROBANTES</p><h3>Pedidos listos para documentar</h3></div></header>${eligible.length?ordersTable(eligible):empty('▧','Aún no hay comprobantes','Cuando un pedido esté completo aparecerá aquí para generar el comprobante.')}</section>`;}
async function movements(){await loadMovements();return `<section class="panel"><header class="panel-head"><div><p class="eyebrow">TRAZABILIDAD</p><h3>Movimientos de inventario</h3></div><button class="button primary" data-action="inventory-adjustment">Registrar ajuste</button></header><div class="activity-list roomy">${state.movements.length?state.movements.map(formatMovement).join(''):empty('↺','Sin movimientos','Las entradas, reservas, salidas y ajustes aparecerán aquí.')}</div></section>`;}

async function reports(){
 const r=await loadReports();
 const bars=r.monthly.length?r.monthly.map(([m,v])=>{const max=Math.max(...r.monthly.map(x=>x[1]),1);const h=Math.max(8,Math.round(v/max*100));return `<div class="report-bar-item"><div class="report-bar" style="height:${h}%"></div><b>${escapeHtml(m)}</b><span>${money(v)}</span></div>`}).join(''):`<div class="empty-mini">Aún no hay ventas entregadas para graficar.</div>`;
 return `<section class="welcome"><div><p class="eyebrow">INTELIGENCIA COMERCIAL</p><h2>Reportes de LIHEN</h2><p>Lectura clara de ventas, productos y operación.</p></div></section>
 <div class="metrics-grid">${metric('$','Ventas totales',money(r.revenue),`${r.completed} pedidos + ${r.quickSales} ventas rápidas`,'green')}${metric('🛒','Ventas rápidas',money(r.quickRevenue),`${r.quickSales} ventas inmediatas`,'gold')}${metric('✓','Pagos de pedidos',money(r.paid),'Pedidos entregados y pagados','gold')}${metric('Ø','Ticket promedio',money(r.average),'Promedio entre ventas cerradas','rose')}${metric('▦','Catálogo publicado',`${r.visible}/${r.totalProducts}`,'Productos visibles en la web','gold')}</div>
 <div class="dashboard-grid"><section class="panel span-2"><header class="panel-head"><div><p class="eyebrow">TENDENCIA</p><h3>Ventas por mes</h3></div></header><div class="report-chart">${bars}</div></section>
 <section class="panel"><header class="panel-head"><div><p class="eyebrow">PRODUCTOS</p><h3>Más solicitados</h3></div></header>${r.topProducts.length?`<div class="ranking">${r.topProducts.map((p,i)=>`<div><span>${i+1}</span><div><b>${escapeHtml(p.name)}</b><small>${p.units} unidad(es)</small></div><strong>${money(p.revenue)}</strong></div>`).join('')}</div>`:empty('↗','Sin datos todavía','Los productos más vendidos aparecerán aquí.')}</section>
 <section class="panel"><header class="panel-head"><div><p class="eyebrow">RED OPERATIVA</p><h3>Capacidad actual</h3></div></header><div class="settings-list"><div><span>Proveedores activos</span><b>${r.activeSuppliers}</b></div><div><span>Productos registrados</span><b>${r.totalProducts}</b></div><div><span>Productos publicados</span><b>${r.visible}</b></div><div><span>Pedidos entregados</span><b>${r.completed}</b></div></div></section></div>`;
}

async function settings(){return `<div class="settings-grid"><section class="panel"><p class="eyebrow">NEGOCIO</p><h3>Configuración general</h3><div class="settings-list"><div><span>Nombre comercial</span><b>LIHEN.CO</b></div><div><span>Ciudad operativa</span><b>Cali</b></div><div><span>Promesa de entrega</span><b>Hasta 3 días hábiles</b></div><div><span>Domicilio inauguración</span><b>${money(0)}</b></div></div></section><section class="panel"><p class="eyebrow">SEGURIDAD</p><h3>Acceso administrativo</h3><div class="security-card"><span>✓</span><div><b>Supabase Auth + RLS</b><p>Solo las cuentas autorizadas pueden consultar o modificar información.</p></div></div><div class="settings-list"><div><span>Usuaria actual</span><b>${escapeHtml(state.profile?.full_name||'—')}</b></div><div><span>Rol</span><b>Cofundadora</b></div><div><span>Estado</span><b>Activo</b></div></div></section><section class="panel span-2"><p class="eyebrow">ENLACES OFICIALES</p><h3>Canales LIHEN.CO</h3><div class="official-links"><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.catalogUrl}">Tienda virtual</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.instagramUrl}">Instagram</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.facebookUrl}">Facebook</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.tiktokUrl}">TikTok</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.whatsappGroupUrl}">Grupo de WhatsApp</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.whatsappShopUrl}">Comprar / consultar</a></div><div class="callout"><b>Uso del WhatsApp corporativo</b><p>Los botones abren el chat con el cliente y un mensaje listo para revisar. Asegúrate de tener abierta la cuenta corporativa de LIHEN en WhatsApp Web.</p></div></section></div>`;}

