import { state, loadDashboard, loadProducts, loadOrders, loadQuickSales, loadCustomers, loadSuppliers, loadMovements, loadReports, loadSupplierPurchases, loadFinancialAccounts } from './store.js';
import { $, escapeHtml, money, dateTime, statusLabel, whatsappUrl } from './utils.js';
import { badge, empty, formatMovement, metric, modal, spinner, totals } from './ui.js';
import { APP_CONFIG } from './config.js';
export { showOrder } from './order-workflow.js';
import { quickSaleReceipt } from './sales.js';
import { summarizeAccounts } from './services/financial-account-service.js';

export async function renderRoute(){
 const root=$('#viewRoot'); if(root) root.innerHTML=spinner();
 const views={dashboard,orders,'quick-sales':quickSales,inventory,suppliers,customers,receipts,movements,reports,cash,settings};
 try{return await views[state.route]();}catch(e){console.error(e); return `<div class="alert danger state-message" role="alert"><b>No pudimos cargar este módulo.</b><p>${escapeHtml(e.message)}</p><button class="button secondary" type="button" data-action="retry-route">Intentar de nuevo</button></div>`;}
}
async function dashboard(){ const d=await loadDashboard(); return `<section class="welcome"><div><p class="eyebrow">RESUMEN OPERATIVO</p><h2>Hola, ${escapeHtml((state.profile?.full_name||'Cofundadora').split(' ')[0])}</h2><p>Estas son las prioridades de LIHEN en este momento.</p></div><button class="button secondary" data-route="orders">Ver pedidos activos →</button></section><div class="quick-actions"><button class="quick-action" data-action="new-order">▤<span>Nuevo pedido</span></button><button class="quick-action" data-action="new-quick-sale">🛒<span>Venta rápida</span></button><button class="quick-action" data-action="new-customer">♡<span>Nuevo cliente</span></button><button class="quick-action" data-action="inventory-adjustment">↺<span>Ingresar stock</span></button><button class="quick-action" data-action="import-inventory">⇧<span>Importar nuevo Excel</span></button></div>
<div class="metrics-grid">${metric('▤','Pedidos activos',d.activeOrders,'Requieren seguimiento','rose')}${metric('✓','Pedidos completos',d.readyOrders,'Listos para confirmar','green')}${metric('▦','Unidades disponibles',d.unitsAvailable,'Stock físico libre','gold')}${metric('!','Alertas de inventario',d.lowStock,'En mínimo o sin stock','red')}${metric('🛒','Ventas rápidas hoy',d.quickSalesToday,money(d.quickSalesRevenue),'green')}</div>
<div class="dashboard-grid"><section class="panel span-2"><header class="panel-head"><div><p class="eyebrow">OPERACIÓN</p><h3>Pedidos recientes</h3></div><button class="text-button" data-route="orders">Ver todos</button></header>${ordersTable(d.recentOrders)}</section><section class="panel"><header class="panel-head"><div><p class="eyebrow">ACTIVIDAD</p><h3>Últimos movimientos</h3></div></header><div class="activity-list">${d.movements.length?d.movements.map(formatMovement).join(''):empty('↺','Sin movimientos','Los cambios de inventario aparecerán aquí.')}</div></section></div>
<div class="insight-strip"><div><span>Productos visibles en web</span><b>${d.visibleProducts}</b></div><div><span>Unidades pendientes de recibir</span><b>${d.pendingToReceive}</b></div><div><span>Clientes registrados</span><b>${d.customers}</b></div><div><span>Compromiso de entrega</span><b>Hasta 3 días hábiles</b></div></div>`; }
function ordersTable(rows){ if(!rows?.length)return empty('▤','No hay pedidos','Crea el primer pedido cuando llegue una consulta por WhatsApp.','<button class="button primary" data-action="new-order">Crear pedido</button>'); return `<div class="table-scroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Estado</th><th>Total</th><th>Fecha</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${escapeHtml(o.order_number)}</b></td><td>${escapeHtml(o.customer?.full_name||'—')}</td><td>${badge(o.status)}</td><td><b>${money(o.total)}</b></td><td>${dateTime(o.created_at)}</td><td><button class="row-action" data-order-id="${o.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div>`; }
async function orders(){await loadOrders(); return `<section class="page-tools"><div class="search"><span>⌕</span><input id="orderSearch" placeholder="Buscar por número de pedido"></div><select id="orderStatus"><option value="">Todos los estados</option>${['solicitud_recibida','validando_disponibilidad','pendiente_proveedor','productos_solicitados','recepcion_parcial','pedido_completo','esperando_medio_pago','confirmado_cliente','preparando_entrega','enviado','entregado','cancelado'].map(x=>`<option value="${x}">${statusLabel(x)}</option>`).join('')}</select><button class="button primary" data-action="new-order">+ Nuevo pedido</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">PEDIDOS LIHEN</p><h3>${state.orders.length} registros</h3></div></header><div id="ordersContent">${ordersTable(state.orders)}</div></section>`;}

function quickSalesTable(rows){
  if(!rows?.length)return empty('🛒','No hay ventas rápidas','Registra una venta presencial pagada al instante.','<button class="button primary" data-action="new-quick-sale">Registrar venta</button>');
  return `<div class="table-scroll"><table><thead><tr><th>Venta</th><th>Cliente</th><th>Pago</th><th>Total</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td><b>${escapeHtml(s.sale_number)}</b></td><td>${escapeHtml(s.customer?.full_name||'Consumidor final')}</td><td>${escapeHtml(String(s.payment_method||'').replaceAll('_',' '))}</td><td><b>${money(s.total)}</b></td><td>${dateTime(s.created_at)}</td><td>${badge(s.status)}</td><td><button class="row-action" data-quick-sale-id="${s.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div>`;
}
async function quickSales(){
  await loadQuickSales();
  return `<section class="page-tools"><div class="search"><span>⌕</span><input id="quickSaleSearch" placeholder="Buscar por número de venta"></div><button class="button primary" data-action="new-quick-sale">+ Nueva venta rápida</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">VENTAS PRESENCIALES</p><h3>${state.quickSales.length} registros</h3></div><div class="callout compact-callout"><b>Pago inmediato</b><p>Descuenta stock al guardar. No crea reservas ni exige teléfono.</p></div></header>${quickSalesTable(state.quickSales)}</section>`;
}

async function inventory(){await loadProducts(); return `<section class="page-tools"><div class="search"><span>⌕</span><input id="productSearch" placeholder="Buscar producto"></div><select id="productVisibility"><option value="">Todos</option><option value="visible">Visibles en la web</option><option value="hidden">Ocultos</option></select><button class="button secondary" data-action="import-inventory">Importar nuevo Excel</button><button class="button secondary" data-action="export-inventory">Descargar inventario actual</button><button class="button primary" data-action="new-product">+ Nuevo producto</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">INVENTARIO Y CATÁLOGO</p><h3>${state.products.length} productos</h3></div><button class="button secondary" data-action="import-catalog">Importar catálogo CSV</button></header>${productTable(state.products)}</section>`;}
function productTable(rows){if(!rows.length)return empty('▦','Sin productos','Importa el catálogo maestro o registra un producto.');return `<div class="table-scroll"><table><thead><tr><th>Producto</th><th>Estado web</th><th>Físico</th><th>Reservado</th><th>Libre</th><th>Pendiente</th><th>Precio</th><th></th></tr></thead><tbody>${rows.map(p=>{const i=p.inventory?.[0]||{};return `<tr><td><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.catalog_code||p.sku||'Sin código')} · ${escapeHtml(p.category||'Sin categoría')}</small></td><td>${(()=>{const hasImage=Boolean((p.main_image_url||'').trim())||(p.product_images||[]).some(img=>Boolean((img.public_url||'').trim()));if(!p.visible_on_website)return '<span class="status neutral">Oculto</span>';if(p.status!=='activo')return '<span class="status neutral">Inactivo</span>';if(!hasImage)return '<span class="status warning">Pendiente foto</span>';return '<span class="status success">Publicado</span>'})()}</td><td>${i.physical_stock??0}</td><td>${i.reserved_stock??0}</td><td><b>${i.available_stock??0}</b></td><td>${i.pending_stock??0}</td><td><b>${money(p.sale_price)}</b></td><td><button class="row-action" data-edit-product="${p.id}">Editar</button></td></tr>`}).join('')}</tbody></table></div>`;}
async function suppliers(){await loadSuppliers();return `<section class="page-tools"><div class="search"><span>⌕</span><input id="supplierSearch" placeholder="Buscar proveedor"></div><button class="button secondary" data-action="import-suppliers">Importar proveedores</button><button class="button secondary" data-action="import-supplier-purchases">Importar compras</button><button class="button secondary" data-action="export-supplier-purchases">Exportar consolidado</button><button class="button ghost" data-action="download-supplier-purchase-template">Plantilla vacía</button><button class="button primary" data-action="new-supplier">+ Nuevo proveedor</button></section><div class="cards-grid">${state.suppliers.length?state.suppliers.map(s=>`<article class="supplier-card"><header><div class="supplier-logo">${escapeHtml(s.business_name.slice(0,2).toUpperCase())}</div>${badge(s.active?'activo':'oculto')}</header><h3>${escapeHtml(s.business_name)}</h3><p>${escapeHtml(s.contact_name||'Sin contacto registrado')}</p><dl><div><dt>WhatsApp</dt><dd>${escapeHtml(s.whatsapp)}</dd></div><div><dt>Ciudad</dt><dd>${escapeHtml(s.city||'—')}</dd></div><div><dt>Entrega habitual</dt><dd>${s.average_delivery_days??'—'} días</dd></div><div><dt>Productos asociados</dt><dd>${s.supplier_products?.length||0}</dd></div></dl><footer><button class="button primary" data-new-supplier-purchase="${s.id}">Nueva compra</button><button class="button secondary" data-new-historical-purchase="${s.id}">Compra histórica</button><button class="button secondary" data-view-supplier-purchases="${s.id}">Ver compras</button><a class="button whatsapp" target="_blank" href="${whatsappUrl(s.whatsapp,'Hola, buen día. Somos LIHEN.CO y queremos consultar disponibilidad de algunos productos.')}">Consultar por WhatsApp</a><button class="button ghost" data-edit-supplier="${s.id}">Editar</button></footer></article>`).join(''):empty('◇','Sin proveedores','Registra proveedores para generar solicitudes por WhatsApp.')}</div>`;}
async function customers(){await loadCustomers();return `<section class="page-tools"><div class="search"><span>⌕</span><input id="customerSearch" placeholder="Buscar cliente o WhatsApp"></div><button class="button secondary" data-action="import-customers">Importar</button><button class="button primary" data-action="new-customer">+ Nuevo cliente</button></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">BASE DE CLIENTES</p><h3>${state.customers.length} clientes</h3></div></header><div class="table-scroll"><table><thead><tr><th>Cliente</th><th>WhatsApp</th><th>Dirección principal</th><th>Notas</th><th></th></tr></thead><tbody>${state.customers.map(c=>`<tr><td><b>${escapeHtml(c.full_name)}</b><small>${escapeHtml(c.email||'Sin correo')}</small></td><td>${escapeHtml(c.whatsapp)}</td><td>${escapeHtml(c.addresses?.find(a=>a.is_default)?.address_line||c.addresses?.[0]?.address_line||'—')}</td><td>${escapeHtml(c.notes||'—')}</td><td><div class="row-actions"><button class="row-action" data-edit-customer="${c.id}">Editar</button><a class="row-action" target="_blank" href="${whatsappUrl(c.whatsapp,`Hola ${c.full_name}, te saludamos desde LIHEN.CO.`)}">WhatsApp</a></div></td></tr>`).join('')}</tbody></table></div></section>`;}
async function receipts(){await loadOrders();const eligible=state.orders.filter(o=>['pedido_completo','esperando_medio_pago','confirmado_cliente','preparando_entrega','enviado','entregado'].includes(o.status));return `<section class="panel"><header class="panel-head"><div><p class="eyebrow">COMPROBANTES</p><h3>Pedidos listos para documentar</h3></div></header>${eligible.length?ordersTable(eligible):empty('▧','Aún no hay comprobantes','Cuando un pedido esté completo aparecerá aquí para generar el comprobante.')}</section>`;}
async function movements(){await loadMovements();return `<section class="panel"><header class="panel-head"><div><p class="eyebrow">TRAZABILIDAD</p><h3>Movimientos de inventario</h3></div><button class="button primary" data-action="inventory-adjustment">Registrar ajuste</button></header><div class="activity-list roomy">${state.movements.length?state.movements.map(formatMovement).join(''):empty('↺','Sin movimientos','Las entradas, reservas, salidas y ajustes aparecerán aquí.')}</div></section>`;}

async function reports(){
 const r=await loadReports();
 const bars=r.monthly.length?r.monthly.map(([m,v])=>{const max=Math.max(...r.monthly.map(x=>x[1]),1);const h=Math.max(8,Math.round(v/max*100));return `<div class="report-bar-item"><div class="report-bar" style="height:${h}%"></div><b>${escapeHtml(m)}</b><span>${money(v)}</span></div>`}).join(''):`<div class="empty-mini">Aún no hay ventas cerradas para graficar.</div>`;
 const alertCounts=r.alerts.reduce((acc,a)=>{acc[a.severity]=(acc[a.severity]||0)+1;return acc;},{critical:0,warning:0,info:0});
 const alerts=r.alerts.length?`<section class="panel span-2"><header class="panel-head"><div><p class="eyebrow">CONTROL FINANCIERO</p><h3>Alertas de LIHEN</h3></div><div class="alert-summary"><span class="badge danger">${alertCounts.critical} críticas</span><span class="badge warning">${alertCounts.warning} advertencias</span><span class="badge info">${alertCounts.info} informativas</span></div></header><div class="financial-alert-list">${r.alerts.slice(0,12).map(a=>`<article class="financial-alert ${a.severity}"><b>${escapeHtml(a.title)}</b><p>${escapeHtml(a.message)}</p></article>`).join('')}</div></section>`:'';
 return `<section class="welcome"><div><p class="eyebrow">INTELIGENCIA COMERCIAL</p><h2>Reportes de LIHEN</h2><p>Ventas, dinero real, compras y obligaciones sin mezclar conceptos.</p></div></section>
 <div class="metrics-grid">${metric('$','Ventas registradas',money(r.revenue),`${r.completed} pedidos + ${r.quickSales} ventas rápidas`,'green')}${metric('$','Ingresos cobrados',money(r.collectedIncome),'Dinero que realmente entró','gold')}${metric('−','Pagos a proveedores',money(r.supplierPaid),'Salidas por compras','rose')}${metric('↕','Flujo neto',money(r.netCashFlow),'Ingresos menos egresos pagados',r.netCashFlow>=0?'green':'rose')}${metric('$','Dinero disponible',money(r.availableMoney),'Suma actual de cuentas activas','gold')}</div>
 <div class="metrics-grid">${metric('N','Saldo Nequi',money(r.nequiBalance),'Cuenta digital','rose')}${metric('$','Efectivo físico',money(r.cashBalance),'Caja disponible','gold')}${metric('▦','Compras registradas',money(r.purchasesTotal),'Mercancía comprada','gold')}${metric('!','Cuentas por pagar',money(r.accountsPayable),'Saldo pendiente a proveedores','rose')}${metric('≈','Utilidad bruta estimada',money(r.grossProfit),`Ventas menos costo estimado (${money(r.cogs)})`,r.grossProfit>=0?'green':'rose')}</div>
 <div class="dashboard-grid">${alerts}<section class="panel span-2"><header class="panel-head"><div><p class="eyebrow">TENDENCIA</p><h3>Ventas por mes</h3></div></header><div class="report-chart">${bars}</div></section>
 <section class="panel"><header class="panel-head"><div><p class="eyebrow">PRODUCTOS</p><h3>Más vendidos</h3></div></header>${r.topProducts.length?`<div class="ranking">${r.topProducts.map((p,i)=>`<div><span>${i+1}</span><div><b>${escapeHtml(p.name)}</b><small>${p.units} unidad(es)</small></div><strong>${money(p.revenue)}</strong></div>`).join('')}</div>`:empty('↗','Sin datos todavía','Los productos más vendidos aparecerán aquí.')}</section>
 <section class="panel"><header class="panel-head"><div><p class="eyebrow">OPERACIÓN</p><h3>Capacidad actual</h3></div></header><div class="settings-list"><div><span>Proveedores activos</span><b>${r.activeSuppliers}</b></div><div><span>Productos registrados</span><b>${r.totalProducts}</b></div><div><span>Productos publicados</span><b>${r.visible}</b></div><div><span>Unidades vendidas</span><b>${r.soldUnits}</b></div><div><span>Unidades recibidas</span><b>${r.receivedUnits}</b></div><div><span>Ticket promedio</span><b>${money(r.average)}</b></div></div><div class="callout"><b>Utilidad estimada</b><p>El costo se calcula con el costo actual del producto. Para contabilidad definitiva se requiere conservar el costo histórico exacto de cada venta.</p></div></section></div>`;
}


async function cash(){
  await loadFinancialAccounts();
  const summary=summarizeAccounts(state.financialAccounts);
  return `<div class="metrics-grid">${metric('$','Saldo Nequi',money(summary.nequi),'Cuenta digital','rose')}${metric('$','Efectivo físico',money(summary.cash),'Caja disponible','gold')}${metric('$','Dinero total LIHEN',money(summary.total),'Suma de cuentas activas','green')}</div><section class="panel"><header class="panel-head"><div><p class="eyebrow">CAJA Y CUENTAS</p><h3>Cuentas registradas</h3></div><div class="row-actions"><button class="button secondary" data-action="transfer-financial-funds">Transferir</button><button class="button primary" data-action="new-financial-movement">+ Movimiento</button></div></header><div class="table-scroll"><table><thead><tr><th>Cuenta</th><th>Saldo actual</th><th>Saldo inicial</th><th>Estado</th></tr></thead><tbody>${state.financialAccounts.map(a=>`<tr><td><b>${escapeHtml(a.name)}</b></td><td>${money(a.current_balance)}</td><td>${money(a.initial_balance)}</td><td>${a.initial_balance_configured?'Configurada':`<button class="row-action" data-configure-account="${a.id}">Configurar saldo</button>`}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><header class="panel-head"><div><p class="eyebrow">HISTORIAL</p><h3>Movimientos recientes</h3></div></header><div class="table-scroll"><table><thead><tr><th>Fecha</th><th>Cuenta</th><th>Tipo</th><th>Valor</th><th>Saldo posterior</th><th></th></tr></thead><tbody>${state.financialMovements.map(m=>`<tr><td>${dateTime(m.occurred_at)}</td><td>${escapeHtml(m.account?.name||'—')}</td><td>${escapeHtml(statusLabel(m.movement_type))}</td><td>${money(m.amount)}</td><td>${money(m.balance_after)}</td><td>${m.status==='activo'&&!['saldo_inicial','transferencia_entrada','transferencia_salida','reversion'].includes(m.movement_type)?`<button class="row-action danger" data-reverse-financial-movement="${m.id}">Reversar</button>`:'—'}</td></tr>`).join('')}</tbody></table></div></section>`;
}
async function settings(){return `<div class="settings-grid"><section class="panel"><p class="eyebrow">NEGOCIO</p><h3>Configuración general</h3><div class="settings-list"><div><span>Nombre comercial</span><b>LIHEN.CO</b></div><div><span>Ciudad operativa</span><b>Cali</b></div><div><span>Promesa de entrega</span><b>Hasta 3 días hábiles</b></div><div><span>Domicilio inauguración</span><b>${money(0)}</b></div></div></section><section class="panel"><p class="eyebrow">SEGURIDAD</p><h3>Acceso administrativo</h3><div class="security-card"><span>✓</span><div><b>Supabase Auth + RLS</b><p>Solo las cuentas autorizadas pueden consultar o modificar información.</p></div></div><div class="settings-list"><div><span>Usuaria actual</span><b>${escapeHtml(state.profile?.full_name||'—')}</b></div><div><span>Rol</span><b>Cofundadora</b></div><div><span>Estado</span><b>Activo</b></div></div></section><section class="panel span-2"><p class="eyebrow">ENLACES OFICIALES</p><h3>Canales LIHEN.CO</h3><div class="official-links"><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.catalogUrl}">Tienda virtual</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.instagramUrl}">Instagram</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.facebookUrl}">Facebook</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.tiktokUrl}">TikTok</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.whatsappGroupUrl}">Grupo de WhatsApp</a><a target="_blank" rel="noopener noreferrer" href="${APP_CONFIG.whatsappShopUrl}">Comprar / consultar</a></div><div class="callout"><b>Uso del WhatsApp corporativo</b><p>Los botones abren el chat con el cliente y un mensaje listo para revisar. Asegúrate de tener abierta la cuenta corporativa de LIHEN en WhatsApp Web.</p></div></section></div>`;}

